name: Deploy to production 🚀

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.GEL_VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.GEL_ORG_ID}}
          vercel-project-id: ${{ secrets.GEL_SCRIBE_PROJECT_ID}}
          # TODO: Do we always need to specify this public endpoint? Does vercel not run api in build for SSR?
          vercel-args: '--prod -e NEXT_PUBLIC_VERCEL_URL=https://scribedao.graphcdn.app'
          github-comment: false # No need to comment preview link
          working-directory: ./

      - name: Push schema
        run: npx graphcdn push schema
        env:
          GRAPHCDN_TOKEN: ${{ secrets.GRAPHCDN_TOKEN }}
