name: GraphQL Inspector

on:
  pull_request:
    branches: [main]

jobs:
  check-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Inspect Schema changes
        uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'schema.graphql' # important to define a path to schema file, without a branch
          endpoint: 'https://retweet.scribedao.com/api/graphql'
