name: GraphQL Inspector

on:
  pull_request:
    branches: [main]

jobs:
  check-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Inspect Schema changes
        uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'schema.graphql'
          endpoint: 'https://retweet.scribedao.com/api/graphql'
