name: Generate Deploy Preview 🚀

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.GEL_VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.GEL_ORG_ID}}
          vercel-project-id: ${{ secrets.GEL_SCRIBE_PROJECT_ID}}
          working-directory: ./
